### ISSUE TITLE
Support REQUEST_METHOD variable in IIS URL Rewrite file parsing

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/BasicMiddleware#293]
See: #191

**Comment by mikaelm12** [comment]
Done: f2676babd3b7780573c40800dd916c7ad9195285

**Comment by KallDrexx** [comment]
Was this actually added to the 2.0.6 release?  I have `<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />` and I"m still getting the error that this is an unrecognized parameter

**Comment by mikaelm12** [comment]
This was put into the 2.0.6 milestone but I believe was actually meant to go into the next patch version since the changes for 2.0.6 had already been locked down at the time. This change is currently available in the 2.1 preview-1 though. .
